<a href="https://colab.research.google.com/github/RYEONGRYEONG/Python/blob/main/7_Working_with_External_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 외부 라이브러리 작업
    # 가져오기, 연산자 오버로딩 및 외부 라이브러리 세계로의 모험을 위한 생존 팁

"""
이 자습서에서는 Python의 가져오기에 대해 배우고 익숙하지 않은 라이브러리(및 라이브러리가 반환하는 개체) 작업에 대한 몇 가지 팁을 얻고 연산자 오버로딩에 대해 자세히 알아봅니다.¶
"""
""""""

''

In [ ]:
# 임포트
"""
지금까지 우리는 언어에 내장된 유형과 함수에 대해 이야기했습니다.

그러나 Python의 가장 좋은 점 중 하나(특히 데이터 과학자인 경우)는 Python용으로 작성된 수많은 고품질 사용자 지정 라이브러리입니다.

이러한 라이브러리 중 일부는 "표준 라이브러리"에 있습니다.
즉, Python을 실행하는 모든 위치에서 찾을 수 있습니다.
다른 라이브러리는 Python과 함께 제공되지 않는 경우에도 쉽게 추가할 수 있습니다.

어느 쪽이든 가져오기를 통해 이 코드에 액세스합니다.

표준 라이브러리에서 math를 가져오는 것으로 예제를 시작하겠습니다.
"""

import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [ ]:
"""
math는 모듈입니다.
모듈은 다른 사람이 정의한 변수 모음(원하는 경우 네임스페이스)입니다.
내장 함수 dir()을 사용하여 math에서 모든 이름을 볼 수 있습니다.
"""

print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [ ]:
"""
도트 구문을 사용하여 이러한 변수에 액세스할 수 있습니다.
그들 중 일부는 math.pi와 같은 간단한 값을 참조합니다.
"""

print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [ ]:
"""
그러나 모듈에서 찾을 수 있는 대부분은 math.log와 같은 함수입니다.
"""

math.log(32, 2) //밑이 2고 진수가 32, 2 ** 5

5.0

In [ ]:
"""
물론 math.log가 무엇을 하는지 모른다면 help()를 호출할 수 있습니다.
"""

help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [ ]:
00"""
모듈 자체에서 help()를 호출할 수도 있습니다.
이렇게 하면 모듈의 모든 기능과 값에 대한 결합된 문서가 제공됩니다(모듈에 대한 높은 수준의 설명도 포함).
전체 수학 도움말 페이지를 보려면 "출력" 버튼을 클릭하십시오.
"""

help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    cbrt(x, /)
        Return the cube root of x.
    
    ceil(x, /)

In [ ]:
# 기타 가져오기 구문
"""
우리가 수학에서 함수를 자주 사용한다는 것을 안다면 타이핑을 줄이기 위해 더 짧은 별칭으로 함수를 가져올 수 있습니다(이 경우 "math"는 이미 꽤 짧습니다).
"""

import math as mt 
mt.pi

3.141592653589793

In [ ]:
"""
    Pandas, Numpy, Tensorflow 또는 Matplotlib와 같은 인기 있는 특정 라이브러리에서 이 작업을 수행하는 코드를 본 적이 있을 것입니다.
    예를 들어 numpy를 np로 가져오고 pandas를 pd로 가져오는 것이 일반적인 규칙입니다.

as는 단순히 가져온 모듈의 이름을 바꿉니다. 다음과 같은 작업을 수행하는 것과 같습니다.
"""

import math
mt = math # 이 방식보다는 

In [ ]:
"""
수학 모듈의 모든 변수를 자체적으로 참조할 수 있다면 좋지 않을까요?
즉, math.pi 또는 mt.pi 대신 pi를 참조할 수 있다면?
좋은 소식: 우리는 그렇게 할 수 있습니다.
"""

from math import * # math로부터 전체를 다 가져오겠다.
print(pi, log(32, 2))

3.141592653589793 5.0


In [ ]:
"""
import *는 모듈의 모든 변수에 직접 액세스할 수 있도록 합니다(점 접두사 없이).

나쁜 소식: 일부 순수주의자들은 당신이 이렇게 하는 것에 대해 투덜거릴 수 있습니다.

더 나쁘다 : 그들은 일종의 요점이 있습니다.
"""

from math import *
from numpy import *
print(pi, log(32, 2)) # 오류남! math에서도 log가 있고 numpy에도 log가 있기때문

TypeError: return arrays must be of ArrayType

In [ ]:
"""
무슨 일이 일어난?
이전에 작동했습니다!

이러한 종류의 "별표 가져오기"는 때때로 이상하고 디버그하기 어려운 상황으로 이어질 수 있습니다.

이 경우 문제는 math 모듈과 numpy 모듈 모두 log라는 함수가 있지만 의미 체계가 다르다는 것입니다.
numpy second에서 가져오기 때문에 해당 로그는 math에서 가져온 로그 변수를 덮어씁니다(또는 "그림자").

적절한 절충안은 각 모듈에서 필요한 특정 항목만 가져오는 것입니다.
"""

from math import log, pi
from numpy import asarray

In [ ]:
# 하위 모듈
"""
우리는 모듈에 함수나 값을 참조할 수 있는 변수가 포함되어 있음을 보았습니다.
주의해야 할 점은 다른 모듈을 참조하는 변수도 가질 수 있다는 것입니다.
"""

import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:] # 뒤에서 15번째부터 끝까지
     )

numpy.random is a <class 'module'>
it contains names such as... ['set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [ ]:
"""
따라서 위와 같이 numpy를 가져오면 임의의 "하위 모듈"에서 함수를 호출하려면 두 개의 점이 필요합니다.
"""

# Roll 10 dice
rolls = numpy.random.randint(low=1, high=6, size=10) # 6안나오고 5까지 나옴
rolls

array([1, 1, 4, 2, 2, 5, 2, 2, 3, 2])

In [ ]:
# 오, 네가 갈 곳들, 오 네가 보게 될 물건들
"""
따라서 6개의 레슨을 마치면 int, float, bool, list, string 및 dicts를 사용하는 전문가가 됩니다(그렇죠?).

그것이 사실이라 해도 여기서 끝이 아닙니다.
전문적인 작업을 위해 다양한 라이브러리로 작업할 때 작업 방법을 배워야 하는 고유한 유형을 정의한다는 것을 알게 될 것입니다.
예를 들어 그래프 라이브러리 matplotlib로 작업하는 경우 Subplots, Figures, TickMarks 및 Annotations를 나타내는 개체를 정의하는 개체와 접촉하게 됩니다.
pandas 함수는 DataFrames 및 Series를 제공합니다.

이 섹션에서는 이상한 유형으로 작업하기 위한 빠른 생존 가이드를 공유하고 싶습니다.
"""
""""""

''

In [ ]:
# 이상한 물체를 이해하기 위한 세 가지 도구
"""
위의 셀에서 numpy 함수를 호출하면 "배열"이 생성되는 것을 볼 수 있습니다.
우리는 이전에 이와 같은 것을 본 적이 없습니다(어쨌든 이 과정에서는 본 적이 없습니다).
그러나 당황하지 마십시오.
여기에서 도움이 되는 세 가지 친숙한 내장 함수가 있습니다.

1: type() (이게 뭐죠?)
"""

type(rolls)

numpy.ndarray

In [ ]:
"""
2: dir() (무엇을 할 수 있습니까?)
"""

print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__',

In [ ]:
# If I want the average roll, the "mean" method looks promising...
rolls.mean() # mean 값도 돌릴 때마다 바뀜

2.4

In [ ]:
# Or maybe I just want to turn the array into a list, in which case I can use "tolist"
rolls.tolist() #array가 아닌 list로 바뀜, tolist 알아두기!

[1, 1, 4, 2, 2, 5, 2, 2, 3, 2]

In [ ]:
"""
3: help() (자세히 알려주세요)
"""

# That "ravel" attribute sounds interesting. I'm a big classical music fan.
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [ ]:
# Okay, just tell me everything there is to know about numpy.ndarray
# (Click the "output" button to see the novel-length output)
help(rolls)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [ ]:
"""
(물론 온라인 문서를 확인하는 것이 더 나을 수도 있습니다.)

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html
"""
""""""

''

In [ ]:
# 연산자 오버로딩
"""
아래 식의 값은 무엇입니까?
"""

[3, 4, 1, 2, 2, 1] + 10 # 리스트 각 항목에 10씩 더하면 오류가 남

TypeError: can only concatenate list (not "int") to list

In [ ]:
"""
어리석은 질문입니다.
물론 오류입니다.

하지만 어쩌지...
"""

rolls + 10 ## 넘파이에서는 가능함! list에서는 오류

array([11, 11, 14, 12, 12, 15, 12, 12, 13, 12])

In [ ]:
"""
우리는 파이썬이 인덱싱과 슬라이싱을 위한 +, <, in, == 또는 대괄호와 같은 핵심 구문의 동작 방식을 엄격하게 감시한다고 생각할 수 있습니다.
그러나 실제로는 매우 손을 대지 않는 접근 방식이 필요합니다.
새 유형을 정의할 때 추가가 작동하는 방식 또는 해당 유형의 객체가 다른 것과 같다는 것이 의미하는 바를 선택할 수 있습니다.

목록 설계자는 목록을 숫자에 추가하는 것이 허용되지 않기로 결정했습니다.
numpy 배열의 설계자는 다른 방식으로 진행했습니다(배열의 각 요소에 숫자를 추가함).

다음은 numpy 배열이 Python 연산자와 예기치 않게(또는 적어도 목록과 다르게) 어떻게 상호 작용하는지에 대한 몇 가지 예입니다.
"""

# At which indices are the dice less than or equal to 3?
import numpy
rolls = numpy.random.randint(low = 1, high=6; size=10)
rolls <= 3

SyntaxError: ignored

In [ ]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [ ]:
# Get the last element of the second row of our numpy array
x[1,-1]

6

In [ ]:
# Get the last element of the second sublist of our nested list?
xlist[1,-1] # list는 안 됨. 넘파이를 사용함

TypeError: list indices must be integers or slices, not tuple

In [ ]:
"""
numpy의 ndarray 유형은 다차원 데이터 작업에 특화되어 있으므로 자체 인덱싱 논리를 정의하여 각 차원에서 인덱스를 지정하기 위해 튜플로 인덱싱할 수 있습니다.
"""
""""""

''